apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
        env: prod
        app.kubernetes.io/name: auth-service
    spec:
      containers:
        - name: auth-service
          image: estherw66/auth-service:latest
          ports:
            - containerPort: 5400
              name: proxy
              protocol: TCP
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_PASSWORD
            - name: DB_NAME_CONCERT
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_NAME_AUTH
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ASPNETCORE_URLS
              value: http://*:5400
            - name: Secret
              valueFrom:
                secretKeyRef:
                  name: jwt-config
                  key: Secret
            - name: ExpiryTimeFrame
              valueFrom:
                secretKeyRef:
                  name: jwt-config
                  key: ExpiryTimeFrame
            - name: Issuer
              valueFrom:
                secretKeyRef:
                  name: jwt-config
                  key: Issuer
            - name: Audience
              valueFrom:
                secretKeyRef:
                  name: jwt-config
                  key: Audience
            
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  ports:
    - name: proxy
      port: 5400
      protocol: TCP
      targetPort: 5400
  selector:
    app: auth-service
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-config
type: Opaque
data:
  Secret: "aGlVaWxnZHBwbEh5RHBiR0l1amlTT1RLSHFLZm1ocHBETEFUaVhsWWxYTkx6VVJwVVBxa0tFcUdcTFRVc3loUVI="
  ExpiryTimeFrame: "MDA6MDU6MDA="
  Issuer: "bG9jYWxob3N0"
  Audience: "aHR0cDovL2NvbmNlcnQtbWVldHVwL2FwaQ=="
