name: Build and deploy an app to AKS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  CONTAINER_NAME: "yarp-gateway:latest"
  RESOURCE_GROUP: "cm"
  CLUSTER_NAME: "cm-aks-cluster"
  DEPLOYMENT_MANIFEST_PATH: "./deployment.yml"

jobs:
  buildImage:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t "${{ env.DOCKERHUB_USERNAME }}/${{ env.CONTAINER_NAME }}" .

      - name: Push Docker image to Docker Hub
        run: docker push "${{ env.DOCKERHUB_USERNAME }}/${{ env.CONTAINER_NAME }}"
